In [1]:
import pandas as pd

In [14]:
class GapDataProcessor:
    
    def __init__(self, filename):
        self.root_dir = '../'
        self.data = pd.read_csv(self.root_dir + filename, sep='\t')
        self.data = self.process_data(self.data)
        
    def process_data(self, data):
        data = data.loc[(data['type'] == 'centromere') | (data['type'] == 'telomere'), ['chrom', 'chromStart','chromEnd', 'type']]
        data.rename(columns = { 'chrom': 'Chromosome', 'chromStart': 'Start', 'chromEnd': 'End' }, inplace = True)
        data.iloc[:, 0] = data.loc[:, 'Chromosome'].apply(lambda x: x.replace('chr', ''))

        return data
    
    
    def get_centromeres(self):
        centromeres = self.data.copy()
        centromeres = centromeres.loc[centromeres['type'] == 'centromere']
        centromeres.drop(columns='type', inplace=True)
        centromeres.reset_index(drop=True, inplace=True)

        return centromeres
    
    
    def get_telomeres(self):
        telomeres = self.data.copy()
        telomeres = telomeres.loc[telomeres['type'] == 'telomere']
        telomeres.drop(columns='type', inplace=True)
        telomeres = telomeres.reset_index(drop=True)

        return telomeres

In [15]:
pd.set_option('display.max_rows', 1000)

In [16]:
gdp = GapDataProcessor('../datasets/gap.txt')

gdp.data

    Chromosome      Start        End        type
1            1  121535434  124535434  centromere
19           1          0      10000    telomere
40           1  249240621  249250621    telomere
42           2   92326171   95326171  centromere
49           2          0      10000    telomere
58           2  243189373  243199373    telomere
59           3          0      10000    telomere
62           3   90504854   93504854  centromere
65           3  198012430  198022430    telomere
66           4   49660117   52660117  centromere
72           4          0      10000    telomere
78           4  191144276  191154276    telomere
79           5   46405641   49405641  centromere
82           5          0      10000    telomere
85           5  180905260  180915260    telomere
86           6   58830166   61830166  centromere
91           6          0      10000    telomere
99           6  171105067  171115067    telomere
100          7   58054331   61054331  centromere
107          7          0      10000    telomere
116          7  159128663  159138663    telomere
117          8          0      10000    telomere
120          8   43838887   46838887  centromere
126          8  146354022  146364022    telomere
128          9   47367679   50367679  centromere
152          9          0      10000    telomere
170          9  141203431  141213431    telomere
171          X   58632012   61632012  centromere
186          X          0      10000    telomere
196          X  155260560  155270560    telomere
197          Y          0      10000    telomere
206          Y   10104553   13104553  centromere
214          Y   59363566   59373566    telomere
215         10   39254935   42254935  centromere
225         10  135524747  135534747    telomere
226         10          0      10000    telomere
235         11   51644205   54644205  centromere
242         11  134996516  135006516    telomere
243         11          0      10000    telomere
250         12   34856694   37856694  centromere
255         12          0      10000    telomere
258         12  133841895  133851895    telomere
260         13   16000000   19000000  centromere
266         13          0      10000    telomere
268         13  115159878  115169878    telomere
269         14          0      10000    telomere
271         14   16000000   19000000  centromere
273         14  107339540  107349540    telomere
275         15   17000000   20000000  centromere
278         15          0      10000    telomere
285         15  102521392  102531392    telomere
287         16   35335801   38335801  centromere
291         16          0      10000    telomere
296         16   90344753   90354753    telomere
297         17   22263006   25263006  centromere
304         18   15460898   18460898  centromere
308         18          0      10000    telomere
312         18   78067248   78077248    telomere
313         19   24681782   27681782  centromere
315         19          0      10000    telomere
321         19   59118983   59128983    telomere
322         20          0      10000    telomere
325         20   26369569   29369569  centromere
332         20   63015520   63025520    telomere
335         21   11288129   14288129  centromere
339         21          0      10000    telomere
347         21   48119895   48129895    telomere
350         22   13000000   16000000  centromere
353         22          0      10000    telomere
356         22   51294566   51304566    telomere

In [17]:
centromeres = gdp.get_centromeres()

centromeres

   Chromosome      Start        End
0           1  121535434  124535434
1           2   92326171   95326171
2           3   90504854   93504854
3           4   49660117   52660117
4           5   46405641   49405641
5           6   58830166   61830166
6           7   58054331   61054331
7           8   43838887   46838887
8           9   47367679   50367679
9           X   58632012   61632012
10          Y   10104553   13104553
11         10   39254935   42254935
12         11   51644205   54644205
13         12   34856694   37856694
14         13   16000000   19000000
15         14   16000000   19000000
16         15   17000000   20000000
17         16   35335801   38335801
18         17   22263006   25263006
19         18   15460898   18460898
20         19   24681782   27681782
21         20   26369569   29369569
22         21   11288129   14288129
23         22   13000000   16000000

In [18]:
telomeres = gdp.get_telomeres()

telomeres

   Chromosome      Start        End
0           1          0      10000
1           1  249240621  249250621
2           2          0      10000
3           2  243189373  243199373
4           3          0      10000
5           3  198012430  198022430
6           4          0      10000
7           4  191144276  191154276
8           5          0      10000
9           5  180905260  180915260
10          6          0      10000
11          6  171105067  171115067
12          7          0      10000
13          7  159128663  159138663
14          8          0      10000
15          8  146354022  146364022
16          9          0      10000
17          9  141203431  141213431
18          X          0      10000
19          X  155260560  155270560
20          Y          0      10000
21          Y   59363566   59373566
22         10  135524747  135534747
23         10          0      10000
24         11  134996516  135006516
25         11          0      10000
26         12          0      10000
27         12  133841895  133851895
28         13          0      10000
29         13  115159878  115169878
30         14          0      10000
31         14  107339540  107349540
32         15          0      10000
33         15  102521392  102531392
34         16          0      10000
35         16   90344753   90354753
36         18          0      10000
37         18   78067248   78077248
38         19          0      10000
39         19   59118983   59128983
40         20          0      10000
41         20   63015520   63025520
42         21          0      10000
43         21   48119895   48129895
44         22          0      10000
45         22   51294566   51304566